version: '3.8'
services:
  mysql_host:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=mysql_db
    healthcheck:
        test: ["CMD","mysqladmin","ping","-h","localhost"]
        timeout: 5s
        retries: 1
        start_period: 5s
  django:
    image: djangoharshith:1
    restart: always
    ports:
      - "8888:8000"
    depends_on:
        mysql_host:
          condition: service_healthy
