version: '3.9'
services:
  mysql_host:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=mysql_db
    healthcheck:
        # test: "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD"
        test: "mysqladmin ping --silent"
        # test: "mysqladmin ping -u root -p$$MYSQL_ROOT_PASSWORD"
        interval: 1s
        timeout: 1s
        retries: 3
        start_period: 2s
    volumes:
      - mysql_data:/var/lib/mysql:rw

  django:
    # image: ghcr.io/harshithpaladi/mysql-django:latest
    image: mysql-django:6
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   cache_from:
    #     - ghcr.io/harshithpaladi/mysql-django
    #     - type=registry,ref=ghcr.io/harshithpaladi/mysql-django
    #     - mysql-django
    restart: always
    ports:
      - "8888:8000"
    depends_on:
        mysql_host:
          condition: service_healthy
    command: sh -c "python3 manage.py makemigrations App1 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
volumes:
  mysql_data: