version: '3.9'
services:
  mysql_host:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=mysql_db
    healthcheck:
        # test: "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD"
        test: "mysqladmin ping --silent"
        timeout: 5s
        retries: 2
        start_period: 10s
    volumes:
      - mysql_data:/var/lib/mysql:rw

  django:
    image: djangoharshith:2
    restart: always
    ports:
      - "8888:8000"
    depends_on:
        mysql_host:
          condition: service_healthy
volumes:
  mysql_data: